language: perl

os:
 - linux

perl:
 - "5.10"
 - "5.12"
 - "5.14"
 - "5.16"
 - "5.18"
 - "5.20"

env:
 - RELEASE_TESTING=1 NETWORK_TESTING=1 AUTOMATED_TESTING=1

cache:
 - apt
 - ccache

install:
 - sudo apt-get -qq update
 - sudo apt-get -qq install libssl-dev libssh2-1-dev openssh-client openssh-server
 - git config --global user.name "p5-Git-Raw"
 - git config --global user.email "jacquesg@cpan.org"
 - cpanm --quiet --notest Dist::Zilla Dist::Zilla::PluginBundle::Author::ALEXBIO Pod::Coverage::TrustPod
 - cpanm --quiet --notest Devel::Cover::Report::Coveralls Dist::Zilla::App::Command::cover
 - dzil listdeps --missing | cpanm --quiet --notest

script:
 - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
 - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
 - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
 - sudo sed -i 's,ChallengeResponseAuthentication no,ChallengeResponseAuthentication yes,g' /etc/ssh/sshd_config
 - sudo restart ssh
 - dzil cover -ignore_re ^deps -ignore_re CORE -ignore_re ^const -test -report coveralls

notifications:
  email:
    recipients:
     - alessandro@ghedini.me
     - jacquesg@cpan.org
